name: Test and deploy to branch

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: pytest -q

  deploy:
    name: Deploy to branch
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and push yam-indexing-postgres image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-postgres
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/yam-indexing-postgres:latest

      - name: Build and push yam-indexing-indexer image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-indexer
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/yam-indexing-indexer:latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Update branch environment
        env:
          DOCKER_BRANCH: ${{ github.ref_name }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}

          # App env
          YAM_INDEXING_W3_URLS: ${{ secrets.YAM_INDEXING_W3_URLS }}
          YAM_INDEXING_THE_GRAPH_API_KEY: ${{ secrets.YAM_INDEXING_THE_GRAPH_API_KEY }}
          YAM_INDEXING_SUBGRAPH_URL: ${{ vars.YAM_INDEXING_SUBGRAPH_URL }}
          TELEGRAM_ALERT_BOT_TOKEN: ${{ secrets.TELEGRAM_ALERT_BOT_TOKEN }}
          TELEGRAM_ALERT_GROUP_ID: ${{ vars.TELEGRAM_ALERT_GROUP_ID }}

          # Postgres env
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_READER_USER_PASSWORD: ${{ secrets.POSTGRES_READER_USER_PASSWORD }}
          POSTGRES_WRITER_USER_PASSWORD: ${{ secrets.POSTGRES_WRITER_USER_PASSWORD }}
          POSTGRES_EVENT_QUEUE_USER_PASSWORD: ${{ secrets.POSTGRES_EVENT_QUEUE_USER_PASSWORD }}
        run: |
          ssh staging <<EOF
            set -euxo pipefail

            export DOCKER_BRANCH="$DOCKER_BRANCH"
            export DOCKER_REGISTRY="$DOCKER_REGISTRY"

            export YAM_INDEXING_W3_URLS="$YAM_INDEXING_W3_URLS"
            export YAM_INDEXING_THE_GRAPH_API_KEY="$YAM_INDEXING_THE_GRAPH_API_KEY"
            export YAM_INDEXING_SUBGRAPH_URL="$YAM_INDEXING_SUBGRAPH_URL"
            export TELEGRAM_ALERT_BOT_TOKEN="$TELEGRAM_ALERT_BOT_TOKEN"
            export TELEGRAM_ALERT_GROUP_ID="$TELEGRAM_ALERT_GROUP_ID"

            export POSTGRES_USER="$POSTGRES_USER"
            export POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
            export POSTGRES_DB="$POSTGRES_DB"
            export POSTGRES_READER_USER_PASSWORD="$POSTGRES_READER_USER_PASSWORD"
            export POSTGRES_WRITER_USER_PASSWORD="$POSTGRES_WRITER_USER_PASSWORD"
            export POSTGRES_EVENT_QUEUE_USER_PASSWORD="$POSTGRES_EVENT_QUEUE_USER_PASSWORD"

            cd /var/docker/yam-indexing/\$DOCKER_BRANCH
            git pull origin $DOCKER_BRANCH

            docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWD" $DOCKER_REGISTRY

            docker compose --project-name \$DOCKER_BRANCH-yam-indexing --file docker-compose-branch.yml pull
            docker compose --project-name \$DOCKER_BRANCH-yam-indexing --file docker-compose-branch.yml up -d --remove-orphans
          EOF
  